export const books = [
  {
    id: '1',
    title: 'The Mindful Journal',
    coverImage: '/shopbook2.jpg',
    price: 19.99,
    category: 'Journals',
  },
  {
    id: '2',
    title: 'Adventures of Luna',
    coverImage: '/shopbook4.jpg',
    price: 14.50,
    category: 'Kids Books',
  },
  {
    id: '3',
    title: 'Creative Sketch Pad',
    coverImage: '/shopbook1.jpg',
    price: 12.00,
    category: 'Activity Books',
  },
  {
    id: '4',
    title: 'Whispers of the Forest',
    coverImage: '/shopbook5.jpg',
    price: 22.00,
    category: 'Fiction',
  },
  {
    id: '5',
    title: 'Gratitude Daily',
    coverImage: '/shopbook3.jpg',
    price: 18.00,
    category: 'Journals',
  },
  {
    id: '6',
    title: 'Colors and Shapes',
    coverImage: '/shopbook2.jpg',
    price: 11.99,
    category: 'Kids Books',
  },
  {
    id: '7',
    title: 'Brain Games for Adults',
    coverImage: '/shopbook1.jpg',
    price: 16.99,
    category: 'Activity Books',
  },
  {
    id: '8',
    title: 'The Lost Heir',
    coverImage: '/shopbook3.jpg',
    price: 24.50,
    category: 'Fiction',
  },
  {
    id: '9',
    title: 'Journal of Dreams',
    coverImage: '/shopbook4.jpg',
    price: 17.00,
    category: 'Journals',
  },
  {
    id: '10',
    title: 'Magical Bedtime Tales',
    coverImage: '/shopbook5.jpg',
    price: 13.49,
    category: 'Kids Books',
  },
  {
    id: '11',
    title: 'Puzzle Paradise',
    coverImage: '/shopbook2.jpg',
    price: 14.20,
    category: 'Activity Books',
  },
  {
    id: '12',
    title: 'Echoes of Time',
    coverImage: '/shopbook1.jpg',
    price: 21.00,
    category: 'Fiction',
  },
  {
    id: '13',
    title: 'Nature Reflection Log',
    coverImage: '/shopbook3.jpg',
    price: 20.00,
    category: 'Journals',
  },
  {
    id: '14',
    title: 'Fun with Letters',
    coverImage: '/shopbook5.jpg',
    price: 9.99,
    category: 'Kids Books',
  },
  {
    id: '15',
    title: 'Art Therapy for Beginners',
    coverImage: '/shopbook4.jpg',
    price: 15.75,
    category: 'Activity Books',
  },
  {
    id: '16',
    title: 'City of Shadows',
    coverImage: '/shopbook2.jpg',
    price: 23.00,
    category: 'Fiction',
  },
  {
    id: '17',
    title: 'Gratitude Sketch Journal',
    coverImage: '/shopbook1.jpg',
    price: 18.90,
    category: 'Journals',
  },
  {
    id: '18',
    title: 'Animal Alphabet',
    coverImage: '/shopbook3.jpg',
    price: 10.50,
    category: 'Kids Books',
  },
  {
    id: '19',
    title: 'Mind Maze Challenge',
    coverImage: '/shopbook5.jpg',
    price: 16.30,
    category: 'Activity Books',
  },
  {
    id: '20',
    title: 'The Final Ember',
    coverImage: '/shopbook4.jpg',
    price: 25.00,
    category: 'Fiction',
  },
];
